### ISSUE TITLE
Integration with PHPMailer?

### ISSUE THREAD

**Issue by Synchro** [louisameline/php-mail-signature#7]
Hi,

I'm the maintainer of PHPMailer.

Would you be interested in merging your DKIM code back into PHPMailer? It looks like you've put some effort in to make it better, so it would be great to combine the two. I am in the process of allowing BC breaks before a major release, so now would be a good time!

**Comment by louisameline** [comment]
Hi, thanks for your message and your work.
I'd be happy to contribute but I lack time these days, I'm not sure I can make it in a timely manner. I wrote this code 4 years ago and it will require a little work to remember what I had to do, what you changed in PHPMailer since then, and how to bring the two back together. I'll try to take a look at it.

**Comment by Synchro** [comment]
OK, no worries - the PHPMailer code is workable as it is, but any improvements you can make would be approaciated.
